### ISSUE TITLE
dependency bootstrap-1.3.2-core-assets.jar not available

### ISSUE THREAD

**Issue by rgaduput** [AOEpeople/gradle-jenkins-job-dsl-plugin#3]
hi,
failing during the gradle build due to missing dependency jar "bootstrap-1.3.2-core-assets.jar" and it is not available in the search path where it is searching for.
Just trying to run gradle test after repo pull.
Is it this dependency required or can it be excluded ?

FAILURE: Build failed with an exception.
 What went wrong:
Could not resolve all files for configuration ':jenkins-job-dsl-test-support:compileClasspath'.
> Could not find bootstrap-core-assets.jar (org.jenkins-ci.ui:bootstrap:1.3.2).
  Searched in the following locations:
      https://jcenter.bintray.com/org/jenkins-ci/ui/bootstrap/1.3.2/bootstrap-1.3.2-core-assets.jar
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.__

**Comment by panzerfahrer** [comment]
For me it's currently failing with an unresolved `org.netbeans.modules:org-netbeans-insane:RELEASE72` during the task `jobDslTestRuntime`.

Could this be related to gradle/gradle#3666 @carstenlenz ?

**Comment by carstenlenz** [comment]
@panzerfahrer Yes that is somewhat related to that. It seems the Jenkins people put some (javadoc) artifacts in their releases repo but left the impl jars out :/ 
We had some failing builds ourselves with a similiar error. 

@rgaduput @panzerfahrer The best workaround I could find is adding the jenkins public repo (which also includes all transitive dependencies of Jenkins release repo artifacts:
```gradle
repositories {
    maven { url 'http://repo.jenkins-ci.org/public' } // this
    jcenter()
}
```
I'm not sure if I should change the default-repos added by the plugin because the Jenkins people screwed something  up :(

**Comment by carstenlenz** [comment]
Can you try that out and tell me if that helps?

**Comment by panzerfahrer** [comment]
That fixes it: the public repo seems to do the trick and makes my workaround obsolete.
Before, I had `http://repo.jenkins-ci.org/releases` in (for whatever reason).

**Comment by rgaduput** [comment]
Yes it seems doing the trick.
Causing me below issues now, not sure if it is really related to it or something else.

FAILURE: Build failed with an exception.
* What went wrong:
Failed to capture snapshot of input files for task 'compileGroovy' property 'classpath' during up-to-date check.
> Error snapshotting jar [jenkins-core-2.14.jar]
* Try:
Run with --info or --debug option to get more log output.
* Exception is:
org.gradle.api.UncheckedIOException: Failed to capture snapshot of input files for task 'compileGroovy' property 'classpath' during up-to-date check.
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:90)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.<init>(AbstractNamedFileSnapshotTaskStateChanges.java:55)
        at org.gradle.api.internal.changedetection.rules.InputFilesTaskStateChanges.<init>(InputFilesTaskStateChanges.java:28)
        at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:56)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:170)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:85)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)

**Comment by rgaduput** [comment]
Managed to fix it by removing cache and recompile.

**Comment by carstenlenz** [comment]
I consider this issue closed now. 
Feel free to reopen if there are any problems remaining.
Cheers
Carsten
