### ISSUE TITLE
Compilation fails with plugin dependencies resolve issues

### ISSUE THREAD

**Issue by rgaduput** [AOEpeople/gradle-jenkins-job-dsl-plugin#4]
hi,
failing during the gradle build with below.
just running local compilation after repo pull.
Only changes done is the WA suggested to fix missing bootstarp jar AOEpeople/gradle-jenkins-job-dsl-plugin#3

_:jenkins-job-dsl-gradle-plugin:test
com.aoe.gradle.jenkinsjobdsl.FilePluginDependencySpec > resolve file plugin dependencies FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at FilePluginDependencySpec.groovy:42
com.aoe.gradle.jenkinsjobdsl.DslExtensionsSpec > executing jobDslTest FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at DslExtensionsSpec.groovy:98
com.aoe.gradle.jenkinsjobdsl.EnvironmentPassingSpec > executing jobDslTest FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at EnvironmentPassingSpec.groovy:52
4 tests completed, 3 failed
:jenkins-job-dsl-gradle-plugin:test FAILED

Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jenkins-job-dsl-gradle-plugin:test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)_

**Comment by carstenlenz** [comment]
These are failing tests.
They fail because of the same reason as in #3 as these tests set up a test gradle project.

I will release a version of the plugin that replaces the Jenkins `/releases` repo with the Jenkins `/public` repo. I already tested locally that this fixes the failing tests and will prevent the error for other users without the workaround from #3

**Comment by rgaduput** [comment]
OK, thanks.
Waiting for the next release.

**Comment by rgaduput** [comment]
@carstenlenz Have released v2.2.0 already ?
I see it in the release but not in https://plugins.gradle.org/m2 repo.

**Comment by carstenlenz** [comment]
@rgaduput I released just now - sorry but I was missing the bintray keys on my home machine so it was only the tag that got created. It is available in the plugins repo now.

**Comment by rgaduput** [comment]
Thanks alot @carstenlenz 
I see it is available now in repo :+1: .

With new version faced below error, seems like **jenkins-core-2.14.jar** is corrupted in the jenkins repo.
managed to fix with WA (copied good jar to .gradle on local machine)

_Execution failed for task ':jobDslTest'.
> failed to scan jar file for packages (/tools/jenkins/.gradle/caches/modules-2/files-2.1/org.jenkins-ci.main/jenkins-core/2.14/d11221e4cd6033627fed5d64c5a24e64c4516837/jenkins-core-2.14.jar)_

Now i see plugin is working as expected.
But it doesn't give understandable errors when something is wrong with the jobs DSL script. I am running it with **gradble build** is it correct or do i need to execute some other tasks or it is like that only?

For example when i added a syntax error to job DSL script and it thrown below error, which seems bit difficult to understand from the what the actual error is.

_com.aoe.gradle.jenkinsjobdsl.JobScriptsSpec > test DSL script sampleJob.groovy FAILED
    org.spockframework.runtime.UnallowedExceptionThrownError at JobScriptsSpec.groovy:55
        Caused by: javaposse.jobdsl.dsl.DslException at JobScriptsSpec.groovy:51
            Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException at JobScriptsSpec.groovy:51_

**Comment by carstenlenz** [comment]
The checks are executed as a Test with JUnit (Spockframework).
If any test fails you will see the above message. 
Gradle should have also told you that there is a report for inspection. The report contains the actual error message. 
That has nothing to do with this plugin but is simply the way Gradle reports failing tests.
